
                        NumPy

---
Este libro de colab explora algunas operaciones y funciones de Numpy

---

In [3]:
import numpy as np

sample_list = [1, 2, 3]

np.array(sample_list)

array([1, 2, 3])

In [ ]:
my_vector = np.array(['this', 'is', 'a', 'vector'])
np.array(my_vector)

array(['this', 'is', 'a', 'vector'], dtype='<U6')

In [ ]:
my_matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.eye(1)

array([[1.]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(50)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
sample_size = 20
np.random.rand(sample_size)

array([0.29049677, 0.83222294, 0.36455694, 0.91806762, 0.97569484,
       0.05641903, 0.72310048, 0.77691227, 0.02868113, 0.22743504,
       0.44908287, 0.7791311 , 0.38325103, 0.76390934, 0.95124742,
       0.28193892, 0.02433511, 0.85656439, 0.66496507, 0.2216648 ])

In [ ]:
np.random.randn(sample_size)

array([-1.1252755 , -0.75212726, -0.60913455,  0.21476579,  0.99544944,
        0.41485766,  0.84758812, -1.88342335,  0.26566941,  0.90475588,
        0.29583642,  0.41663517, -1.3434071 ,  0.48618701, -0.2011143 ,
        1.57288692,  0.87224751,  0.38394163, -0.5171873 ,  0.18791725])

In [ ]:
low = 0
high = 100
np.random.randint(low, high, sample_size)

array([14, 24, 91, 51, 85, 11, 21, 97, 38, 57, 25, 75, 47, 85, 14, 63, 15,
       90, 52, 58])

In [ ]:
arr = np.array([0,1,2,3,4,5])

arr.reshape(1,6)


array([[0, 1, 2, 3, 4, 5]])

In [6]:
arr = np.array([0,1,2,3,4,5])

arr.shape

(6,)

In [7]:
arr = arr.reshape(2,3)

arr.shape



(2, 3)

In [8]:
arr.reshape(2,3).shape

(2, 3)

In [12]:
simple_array = [1, 2, 3, 4]


In [14]:
simple_array = np.array(simple_array)
simple_array.max()

np.int64(4)

In [16]:
simple_array.argmax()

np.int64(3)

In [17]:
simple_array.min()

np.int64(1)

In [18]:
simple_array.argmin()

np.int64(0)

In [19]:
arr = np.arange(4)

arr

array([0, 1, 2, 3])

In [20]:
2 + arr

array([2, 3, 4, 5])

In [21]:
arr + arr

array([0, 2, 4, 6])

In [22]:
arr - 10

array([-10,  -9,  -8,  -7])

In [25]:
6 * arr


array([ 0,  6, 12, 18])

In [26]:
arr * arr

array([0, 1, 4, 9])

In [27]:
arr / 2


array([0. , 0.5, 1. , 1.5])

In [29]:
arr / arr

<ipython-input-29-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.])

In [30]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081])

In [31]:
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [32]:
np.sin(arr)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [33]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [34]:
np.log(arr)

<ipython-input-34-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [60]:
arr = np.random.rand(5)
arr

array([0.29166733, 0.18395919, 0.68444033, 0.12545908, 0.10003377])

In [61]:
arr = np.round(arr, 5)
arr

array([0.29167, 0.18396, 0.68444, 0.12546, 0.10003])

In [62]:
arr[0]

np.float64(0.29167)

In [65]:
arr[:]

array([0.29167, 0.18396, 0.68444, 0.12546, 0.10003])

In [66]:
arr[1:]

array([0.18396, 0.68444, 0.12546, 0.10003])

In [67]:
arr[1:4]

array([0.18396, 0.68444, 0.12546])

In [68]:
arr

array([0.29167, 0.18396, 0.68444, 0.12546, 0.10003])

In [71]:
arr[:] = 0
arr

array([0., 0., 0., 0., 0.])

In [73]:
arr[2:5] = 0.5
arr

array([0. , 0. , 0.5, 0.5, 0.5])

In [77]:
new_array = np.array([6, 7, 8, 9])

second_new_array = new_array[0:2]

second_new_array

array([6, 7])

In [78]:
second_new_array[1] = 4

second_new_array

array([6, 4])

In [79]:
new_array

array([6, 4, 8, 9])

In [80]:
array_to_copy = np.array([1, 2, 3])

copied_array = array_to_copy.copy()

array_to_copy

array([1, 2, 3])

In [81]:
copied_array

array([1, 2, 3])

In [82]:
copied_array[0] = 9

copied_array

array([9, 2, 3])

In [83]:
array_to_copy

array([1, 2, 3])

In [95]:
mat = np.array([[5, 10, 15],[20, 25, 30],[35, 40, 45]])

mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
mat[0]

array([ 5, 10, 15])

In [91]:
mat[0][-1]

np.int64(15)

In [101]:
mat[1:][:2]

array([[20, 25, 30],
       [35, 40, 45]])

In [102]:
arr = np.array([0.69, 0.94, 0.66, 0.73, 0.83])

arr > 0.7

array([False,  True, False,  True,  True])

In [103]:
arr[arr > 0.7]

array([0.94, 0.73, 0.83])